name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11, 12]
        prefer: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} --${{ matrix.prefer }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: pcov

    - uses: actions/cache@v4
      name: Cache dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: |
        composer require "laravel/framework:^${{ matrix.laravel }}.0" --dev "orchestra/testbench" --no-interaction --${{ matrix.prefer }} --prefer-dist

    - name: Setup in-cluster config
      env:
        TEST_TOKEN: some-token
        TEST_CERT: c29tZS1jZXJ0Cg==
        TEST_NAMESPACE: some-namespace
      run: |
        sudo mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
        echo "$TEST_TOKEN" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/token
        echo "$TEST_CERT" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        echo "$TEST_NAMESPACE" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/namespace
        sudo chmod 644 /var/run/secrets/kubernetes.io/serviceaccount/token
        sudo chmod 644 /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        sudo chmod 644 /var/run/secrets/kubernetes.io/serviceaccount/namespace

    - name: Run tests
      run: |
        vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
